import "./globals.css"
import { Outfit } from 'next/font/google'

export const metadata = {
  title: "AI Study Material Generator",
  description: "Generated by create next app",
}

const AppFont = Outfit({ subsets: ['latin'] })

export default function RootLayout({ children }) {

  return (
    <html lang="en" suppressHydrationWarning={ false }>
      <body cz-shortcut-listen="false" className={ AppFont.className }>
        { children }
      </body>
    </html>
  )
}
