import { ClerkProvider } from "@clerk/nextjs"
import "./globals.css"
import { Outfit } from 'next/font/google'
import Provider from "./provider"
import { Toaster } from "@/components/ui/sonner"

export const metadata = {
  title: "AI Study Material Generator",
  description: "Generated by create next app",
}

const AppFont = Outfit({ subsets: ['latin'] })

export default function RootLayout({ children }) {

  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning={ false }>
        <body cz-shortcut-listen="false" className={ AppFont.className }>
          <Provider>
            { children }
          </Provider>
          <Toaster expand={ true } richColors />
        </body>
      </html>
    </ClerkProvider>
  )
}
